#!/bin/sh

set -eu

runuser -u clamav -- freshclam --config-file=/etc/clamav/freshclam.conf --stdout
runuser -u clamav -- freshclam --daemon --config-file=/etc/clamav/freshclam.conf --stdout &
freshclam_pid=$!

clamd --config-file=/etc/clamav/clamd.conf &
clamd_pid=$!

cleanup() {
  kill "$freshclam_pid" 2>/dev/null || true
  kill "$clamd_pid" 2>/dev/null || true
  wait "$freshclam_pid" 2>/dev/null || true
  wait "$clamd_pid" 2>/dev/null || true
}
trap cleanup EXIT INT TERM

wait "$clamd_pid"
